version: '3.8'

services:
  compiler-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_executor

    env_file:
      - ./go-executor/.env          

    environment:
      - CODE_SHARED_DIR=/tmp/executor

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/executor:/tmp/executor

    networks:
      - secure_net

    restart: unless-stopped

networks:
  secure_net:
    external: true
    name: interview_tier_network